# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=100)),
                ('weights', models.CharField(max_length=300)),
                ('max_score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='question_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
